version: '3.9'
services:
  ai_research_assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
      - "8502:8502"
    container_name: ai_research_assistant
    environment:
      OPENAI_API_KEY: "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"
      BROWSERLESS_API_KEY: "1b98a1a0-5a1f-4467-b5c5-d8bcc3f1902e"
      SERPER_API_KEY: "087da745cf222a686f45fdc857687c4c0bb99ff6"
      PYTHONPATH: "/app"